projects:
  - username: test
    site: test.w6p.ru
    ssl: true
    upstream: 10.213.65.121:8080
    docroot: /home/test/prod/test.ru/current/public
    web_template: bitrix
  - username: test1
    site: test1.w6p.ru
    ssl: true
    upstream: 10.213.65.121:8080
    docroot: /home/test1/prod/test1.ru/current/public
    web_template: bitrix
  - username: test2
    site: test2.w6p.ru
    ssl: true  
    upstream: 10.213.65.121:8080
    docroot: /home/test2/prod/test2.ru/current/public
    web_template: bitrix