---
- name: populate service facts
  service_facts:

- name: create list of services
  set_fact:
    service_list: "{{ service_list|default([]) + [item.name|regex_replace('.service|@')] }}"
  when: item.status | default('disabled') == 'enabled' or item.state == 'running' and item.source == 'sysv'
  loop: "{{ ansible_facts.services.values() | list }}"

- name: delete dublicates from services list
  set_fact:
    service_list: "{{ service_list| unique }}"

- name: monit in list
  set_fact:
    monit_in_list: true
  when: "'monit' in service_list"

- name: configuration python.d plugin for nginx
  include_tasks: nginx_and_web_log_plugin_setup.yml
  when: "'nginx' in service_list or netdata_force_all_plugins_installation"

- name: configuration python.d plugin for apache
  include_tasks: apache_plugin_setup.yml
  when: "'apache2' in service_list or netdata_force_all_plugins_installation"

- name: configuration python.d plugin for mysql
  include_tasks: mysql_plugin_setup.yml
  when: "'mysql' in service_list or netdata_force_all_plugins_installation"

- name: configuration python.d plugin for smartd
  include_tasks: smartd_plugin_setup.yml
  when: "'smartd' in service_list or netdata_force_all_plugins_installation"

- name: configuration python.d plugin for smartd
  include_tasks: smartd_plugin_setup.yml
  when: "'smartd' in service_list or netdata_force_all_plugins_installation"


## вынести вклюение отдельной переменной через when
- name: configuration go.d plugin for prometheus
  include_tasks: prometheus_plugin_setup.yml
