- name: Create apache2 vhosts
  template:
     src: vhost.j2
     dest: /etc/apache2/sites-enabled/{{ item.site }}.conf
  loop: "{{ projects | list }}"
  no_log: True 

- name: Copy custom conf apache2 for vhost
  copy:
    src: "files/custom.d/"
    dest: "/etc/nginx/custom.d/"

- name: check apache configuration
  command: apachectl -t
  ignore_errors: true
  register: apache_syntax_check
  changed_when: false

- name: msmtp
  template:
     src: msmtprc.j2
     dest: /etc/msmtprc
  no_log: True

#- name: DEBUG | Output result 
#  debug:
#    var: apache_syntax_check

- name: show errors
  debug:
    msg: "{{ apache_syntax_check.stderr }}"
  when: apache_syntax_check.rc != 0

- name: reload apache
  systemd: name=apache2 state=reloaded
  when: apache_syntax_check.rc == 0


- name: set php session_clear in cron
  block:
    - name: copy script library session_clear 
      copy:
        src: cron_session_clear.j2
        dest: "/usr/local/sbin/custom.cron_session_clear"
      mode: u=rwx,g=,o=  
    - name: copy cron 
      copy:
        src: "cron.d/tasks"
        dest: "/etc/cron.d/tasks" 
        mode: '0644'
      no_log: True 
    - name: reload cron  
      systemd: name=apache2 state=reloaded