---
- name: install binary
  get_url:
    url: "{{ postfix_exporter_binary_url }}"
    dest: "/usr/local/bin/"
    mode: 0755
  when: not ansible_check_mode
  notify: restart postfix_exporter service

- name: configuration
  template:
    src: default-config.j2
    dest: "/etc/default/{{ postfix_exporter_service_name }}"
  notify: restart postfix_exporter service

- name: create log for postfix_exporter
  file:
    path: /var/log/postfix_exporter_input.log
    state: touch
    owner: postfix
    group: postfix
    mode: u=rw,g=r,o=r

- name: create systemd unit
  template:
    src: systemd-unit.j2
    dest: "/etc/systemd/system/{{ postfix_exporter_service_name }}.service"
  notify:
    - reload postfix_exporter unit
    - restart postfix_exporter service

- meta: flush_handlers

- name: enable systemd unit
  systemd:
    name: "{{ postfix_exporter_service_name }}"
    enabled: true
